compressionLevel: mixed

enableGlobalCache: false

plugins:
  - checksum: 1ca83f34576b91862ca09625e76fb8afcc604d552213a8331704ef5f89fd041ef9372f8aed965948cb7f69fbe957f3aafd8c8638ea9b46fca43e427ed36bde62
    path: .yarn/plugins/@ojkelly/plugin-bundle.cjs
    spec: "https://yarn.build/latest/bundle"

yarnPath: .yarn/releases/yarn-4.0.0-rc.51.cjs
