version: '3.9'

services:
  server:
    image: standardnotes/server
    env_file: .env
    container_name: server_self_hosted
    ports:
      - 3000:3000
      - 3125:3104
    volumes:
      - ./logs:/var/lib/server/logs
      - ./uploads:/opt/bundled/files/packages/files/dist/uploads
    depends_on:
      localstack:
        condition: service_healthy
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - standardnotes_self_hosted
    healthcheck:
      test: curl -s http://localhost:3000
      timeout: 10s
      interval: 5s
      start_period: 10s
    restart: unless-stopped

  localstack:
    image: localstack/localstack:1.4
    container_name: localstack_self_hosted
    expose:
      - 4566
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - standardnotes_self_hosted
    healthcheck:
      test: curl -s http://localhost:4566/_localstack/health
      timeout: 10s
      interval: 5s
      start_period: 60s

  db:
    image: mysql:8
    container_name: db_self_hosted
    environment:
      - MYSQL_DATABASE=standard_notes_db
      - MYSQL_USER=std_notes_user
      - MYSQL_ROOT_PASSWORD=changeme123
      - MYSQL_PASSWORD=changeme123
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted
    healthcheck:
      test: [
        "CMD", 
        "mysqladmin",
        "ping", 
        "-h", "localhost",
        '-u', 'root', 
        '-p$$MYSQL_ROOT_PASSWORD'
      ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  cache:
    image: redis:7
    container_name: cache_self_hosted
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    restart: unless-stopped
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
