export enum StatisticsMeasure {
  Income = 'income',
  PlusSubscriptionInitialMonthlyPaymentsIncome = 'plus-subscription-initial-monthly-payments-income',
  ProSubscriptionInitialMonthlyPaymentsIncome = 'pro-subscription-initial-monthly-payments-income',
  PlusSubscriptionInitialAnnualPaymentsIncome = 'plus-subscription-initial-annual-payments-income',
  ProSubscriptionInitialAnnualPaymentsIncome = 'pro-subscription-initial-annual-payments-income',
  PlusSubscriptionRenewingMonthlyPaymentsIncome = 'plus-subscription-renewing-monthly-payments-income',
  ProSubscriptionRenewingMonthlyPaymentsIncome = 'pro-subscription-renewing-monthly-payments-income',
  PlusSubscriptionRenewingAnnualPaymentsIncome = 'plus-subscription-renewing-annual-payments-income',
  ProSubscriptionRenewingAnnualPaymentsIncome = 'pro-subscription-renewing-annual-payments-income',
  SubscriptionLength = 'subscription-length',
  RegistrationLength = 'registration-length',
  RegistrationToSubscriptionTime = 'registration-to-subscription-time',
  RemainingSubscriptionTimePercentage = 'remaining-subscription-time-percentage',
  Refunds = 'refunds',
  NewCustomers = 'new-customers',
  TotalCustomers = 'total-customers',
  MRR = 'mrr',
  MonthlyPlansMRR = 'monthly-plans-mrr',
  AnnualPlansMRR = 'annual-plans-mrr',
  FiveYearPlansMRR = 'five-year-plans-mrr',
  ProPlansMRR = 'pro-plans-mrr',
  PlusPlansMRR = 'plus-plans-mrr',
}
