export enum SettingName {
  MfaSecret = 'MFA_SECRET',
  ExtensionKey = 'EXTENSION_KEY',
  EmailBackupFrequency = 'EMAIL_BACKUP_FREQUENCY',
  DropboxBackupFrequency = 'DROPBOX_BACKUP_FREQUENCY',
  DropboxBackupToken = 'DROPBOX_BACKUP_TOKEN',
  OneDriveBackupFrequency = 'ONE_DRIVE_BACKUP_FREQUENCY',
  OneDriveBackupToken = 'ONE_DRIVE_BACKUP_TOKEN',
  GoogleDriveBackupFrequency = 'GOOGLE_DRIVE_BACKUP_FREQUENCY',
  GoogleDriveBackupToken = 'GOOGLE_DRIVE_BACKUP_TOKEN',
  MuteFailedBackupsEmails = 'MUTE_FAILED_BACKUPS_EMAILS',
  MuteFailedCloudBackupsEmails = 'MUTE_FAILED_CLOUD_BACKUPS_EMAILS',
  MuteSignInEmails = 'MUTE_SIGN_IN_EMAILS',
  MuteMarketingEmails = 'MUTE_MARKETING_EMAILS',
  ListedAuthorSecrets = 'LISTED_AUTHOR_SECRETS',
  LogSessionUserAgent = 'LOG_SESSION_USER_AGENT',
  RecoveryCodes = 'RECOVERY_CODES',
}
