const TYPES = {
  DBConnection: Symbol.for('DBConnection'),
  Logger: Symbol.for('Logger'),
  Redis: Symbol.for('Redis'),
  SNS: Symbol.for('SNS'),
  SQS: Symbol.for('SQS'),
  S3: Symbol.for('S3'),
  Env: Symbol.for('Env'),

  // Repositories
  ItemRepository: Symbol.for('ItemRepository'),
  SharedVaultRepository: Symbol.for('SharedVaultRepository'),
  SharedVaultUserRepository: Symbol.for('SharedVaultUserRepository'),
  ContactRepository: Symbol.for('ContactRepository'),
  SharedVaultInviteRepository: Symbol.for('SharedVaultInviteRepository'),
  UserEventRepository: Symbol.for('UserEventRepository'),

  // ORM
  ORMItemRepository: Symbol.for('ORMItemRepository'),
  ORMSharedVaultRepository: Symbol.for('ORMSharedVaultRepository'),
  ORMSharedVaultUserRepository: Symbol.for('ORMSharedVaultUserRepository'),
  ORMContactRepository: Symbol.for('ORMContactRepository'),
  ORMSharedVaultInviteRepository: Symbol.for('ORMSharedVaultInviteRepository'),
  ORMUserEventRepository: Symbol.for('ORMUserEventRepository'),

  // Middleware
  AuthMiddleware: Symbol.for('AuthMiddleware'),

  // Projectors
  ItemProjector: Symbol.for('ItemProjector'),
  SavedItemProjector: Symbol.for('SavedItemProjector'),
  ItemConflictProjector: Symbol.for('ItemConflictProjector'),
  SharedVaultProjector: Symbol.for('SharedVaultProjector'),
  SharedVaultUserProjector: Symbol.for('SharedVaultUserProjector'),
  ContactProjector: Symbol.for('ContactProjector'),
  SharedVaultInviteProjector: Symbol.for('SharedVaultInviteProjector'),
  UserEventProjector: Symbol.for('UserEventProjector'),

  // Services
  SharedVaultService: Symbol.for('SharedVaultService'),
  SharedVaultUserService: Symbol.for('SharedVaultUserService'),
  ContactService: Symbol.for('ContactService'),
  SharedVaultInviteService: Symbol.for('SharedVaultInviteService'),
  UserEventService: Symbol.for('UserEventService'),

  // Factories
  ItemFactory: Symbol.for('ItemFactory'),
  SharedVaultFactory: Symbol.for('SharedVaultFactory'),
  SharedVaultUserFactory: Symbol.for('SharedVaultUserFactory'),
  ContactFactory: Symbol.for('ContactFactory'),
  SharedVaultInviteFactory: Symbol.for('SharedVaultInviteFactory'),
  UserEventFactory: Symbol.for('UserEventFactory'),

  // env vars
  REDIS_URL: Symbol.for('REDIS_URL'),
  SNS_TOPIC_ARN: Symbol.for('SNS_TOPIC_ARN'),
  SNS_AWS_REGION: Symbol.for('SNS_AWS_REGION'),
  SQS_QUEUE_URL: Symbol.for('SQS_QUEUE_URL'),
  SQS_AWS_REGION: Symbol.for('SQS_AWS_REGION'),
  AUTH_JWT_SECRET: Symbol.for('AUTH_JWT_SECRET'),
  EXTENSIONS_SERVER_URL: Symbol.for('EXTENSIONS_SERVER_URL'),
  AUTH_SERVER_URL: Symbol.for('AUTH_SERVER_URL'),
  S3_AWS_REGION: Symbol.for('S3_AWS_REGION'),
  S3_BACKUP_BUCKET_NAME: Symbol.for('S3_BACKUP_BUCKET_NAME'),
  EMAIL_ATTACHMENT_MAX_BYTE_SIZE: Symbol.for('EMAIL_ATTACHMENT_MAX_BYTE_SIZE'),
  REVISIONS_FREQUENCY: Symbol.for('REVISIONS_FREQUENCY'),
  NEW_RELIC_ENABLED: Symbol.for('NEW_RELIC_ENABLED'),
  VERSION: Symbol.for('VERSION'),
  CONTENT_SIZE_TRANSFER_LIMIT: Symbol.for('CONTENT_SIZE_TRANSFER_LIMIT'),
  MAX_ITEMS_LIMIT: Symbol.for('MAX_ITEMS_LIMIT'),
  FILE_UPLOAD_PATH: Symbol.for('FILE_UPLOAD_PATH'),
  VALET_TOKEN_SECRET: Symbol.for('VALET_TOKEN_SECRET'),
  VALET_TOKEN_TTL: Symbol.for('VALET_TOKEN_TTL'),
  // use cases
  SyncItems: Symbol.for('SyncItems'),
  CheckIntegrity: Symbol.for('CheckIntegrity'),
  GetItem: Symbol.for('GetItem'),
  SaveItem: Symbol.for('SaveItem'),
  CreateSharedVaultFileReadValetToken: Symbol.for('CreateSharedVaultFileReadValetToken'),
  // Handlers
  UserCredentialsChangedEventHandler: Symbol.for('UserCredentialsChangedEventHandler'),
  AccountDeletionRequestedEventHandler: Symbol.for('AccountDeletionRequestedEventHandler'),
  DuplicateItemSyncedEventHandler: Symbol.for('DuplicateItemSyncedEventHandler'),
  EmailBackupRequestedEventHandler: Symbol.for('EmailBackupRequestedEventHandler'),
  ItemRevisionCreationRequestedEventHandler: Symbol.for('ItemRevisionCreationRequestedEventHandler'),
  SharedVaultFileUploadedEventHandler: Symbol.for('SharedVaultFileUploadedEventHandler'),

  ContentDecoder: Symbol.for('ContentDecoder'),
  DomainEventPublisher: Symbol.for('DomainEventPublisher'),
  DomainEventSubscriberFactory: Symbol.for('DomainEventSubscriberFactory'),
  DomainEventFactory: Symbol.for('DomainEventFactory'),
  DomainEventMessageHandler: Symbol.for('DomainEventMessageHandler'),
  HTTPClient: Symbol.for('HTTPClient'),
  ItemService: Symbol.for('ItemService'),
  Timer: Symbol.for('Timer'),
  SyncResponseFactory20161215: Symbol.for('SyncResponseFactory20161215'),
  SyncResponseFactory20200115: Symbol.for('SyncResponseFactory20200115'),
  SyncResponseFactoryResolver: Symbol.for('SyncResponseFactoryResolver'),
  AuthHttpService: Symbol.for('AuthHttpService'),
  ExtensionsHttpService: Symbol.for('ExtensionsHttpService'),
  ItemBackupService: Symbol.for('ItemBackupService'),
  ItemSaveValidator: Symbol.for('ItemSaveValidator'),
  OwnershipFilter: Symbol.for('OwnershipFilter'),
  SharedVaultFilter: Symbol.for('SharedVaultFilter'),
  SharedVaultSnjsVersionFilter: Symbol.for('SharedVaultSnjsVersionFilter'),
  TimeDifferenceFilter: Symbol.for('TimeDifferenceFilter'),
  UuidFilter: Symbol.for('UuidFilter'),
  ContentTypeFilter: Symbol.for('ContentTypeFilter'),
  ContentFilter: Symbol.for('ContentFilter'),
  ItemTransferCalculator: Symbol.for('ItemTransferCalculator'),
  ValetTokenEncoder: Symbol.for('ValetTokenEncoder'),
}

export default TYPES
