export enum AnalyticsActivity {
  GeneralActivity = 'general-activity',
  EditingItems = 'editing-items',
  Login = 'login',
  Register = 'register',
  DeleteAccount = 'DeleteAccount',
  SubscriptionPurchased = 'subscription-purchased',
  SubscriptionRenewed = 'subscription-renewed',
  SubscriptionRefunded = 'subscription-refunded',
  SubscriptionCancelled = 'subscription-cancelled',
  EmailUnbackedUpData = 'email-unbacked-up-data',
  EmailBackup = 'email-backup',
  LimitedDiscountOfferPurchased = 'limited-discount-offer-purchased',
  PaymentFailed = 'payment-failed',
}
