export enum AnalyticsActivity {
  GeneralActivity = 'general-activity',
  GeneralActivityFreeUsers = 'general-activity-free-users',
  GeneralActivityPaidUsers = 'general-activity-paid-users',
  EditingItems = 'editing-items',
  CheckingIntegrity = 'checking-integrity',
  Login = 'login',
  Register = 'register',
  DeleteAccount = 'DeleteAccount',
  SubscriptionPurchased = 'subscription-purchased',
  SubscriptionRenewed = 'subscription-renewed',
  SubscriptionRefunded = 'subscription-refunded',
  SubscriptionCancelled = 'subscription-cancelled',
  SubscriptionExpired = 'subscription-expired',
  EmailUnbackedUpData = 'email-unbacked-up-data',
  EmailBackup = 'email-backup',
  LimitedDiscountOfferPurchased = 'limited-discount-offer-purchased',
  PaymentFailed = 'payment-failed',
  PaymentSuccess = 'payment-success',
  Churn = 'churn',
}
