name: Files Server

concurrency:
  group: files
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/files-server*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: files
      workspace_name: "@standardnotes/files-server"
      package_path: packages/files
    secrets: inherit
