name: Syncing Server

concurrency:
  group: syncing_server
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/syncing-server*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: syncing-server-js
      workspace_name: "@standardnotes/syncing-server"
      package_path: packages/syncing-server
    secrets: inherit
